### PR TITLE
Tidy test suite

### PR DESCRIPTION
**Pull request by lmmx**
This PR tidies up the test suite, using a separate subfolder for non-test modules and standard pytest module naming conventions (broken out of previous PR #9 as requested)

### CODE REVIEW

**Review by koaning — APPROVED** [review]

**Comment by koaning** [comment]
Merge conflict cannot be fixed in the browser, so may need to do that later. Feel free to update if you're able to though!

**Comment by lmmx** [comment]
It doesn't give me the option to resolve unfortunately. The conflicting files were moved in git, but sometimes GitHub inexplicably doesn't match git's merge conflict resolution and says there are ones which you can't see locally.

- `tests/rich-fail.py` -> `tests/assets/rich_fail.py`
- `tests/rich-script.py` -> `tests/assets/rich_script.py`
- `tests/test_basics.py` -> `tests/assets/basics_test.py`

**Comment by lmmx** [comment]
I'm going to revert the names just to avoid the merge conflict hassle

**Comment by lmmx** [comment]
Reverted the names as in #18 so these PRs should be OK to merge (this is a subset of #18 so can be replaced by it if preferred)

**Review by koaning — APPROVED** [review]

**Pull request merged**
